const db = require(`../db`)
const { Product } = require(`../models`)

db.on(`error`, console.error.bind(console, `MongoDB connection error:`))

const products = [
  {
    productName: "Jean-Claude Van Pants",
    productDescription:
      "Action-packed jeans that kick butt! Slim fit, stretchy, and ready for any high-flying stunts you throw at them.",
    productPrice: 49.99,
    productCategory: "Jeans",
    stockQuantity: 120,
    imageUrl: "../images/jean-claude-van-pants.jpg",
    brand: "ActionThreads",
    rating: "4.8",
    onSale: true,
    color: ["Blue", "Black", "Dark Wash"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Sweat Dreams are Made of These",
    productDescription:
      "Soft, cozy sweatpants so comfortable you'll wonder if you're still dreaming. Warning: may cause spontaneous naps.",
    productPrice: 35.0,
    productCategory: "Sweatpants",
    stockQuantity: 150,
    imageUrl: "../images/sweat-dreams-are-made-of-these.jpg",
    brand: "NapWear",
    rating: "4.7",
    onSale: true,
    color: ["Heather Gray", "Navy"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Cargo Not Found",
    productDescription:
      "We lost track of how many pockets these cargo pants have... Seriously, it's like a black hole for your stuff.",
    productPrice: 42.99,
    productCategory: "Cargo Pants",
    stockQuantity: 80,
    imageUrl: "../images/cargo-not-found.jpg",
    brand: "PocketZone",
    rating: "4.5",
    onSale: false,
    color: ["Olive", "Black", "Khaki"],
    size: ["M", "L", "XL"],
  },
  {
    productName: "Flare for the Dramatic",
    productDescription:
      "These bell-bottoms bring drama and flare to any outfit. Perfect for those moments when you need to make an entrance.",
    productPrice: 59.99,
    productCategory: "Flare Pants",
    stockQuantity: 65,
    imageUrl: "../images/flare-for-the-dramatic.jpg",
    brand: "DramaQueen",
    rating: "4.9",
    onSale: false,
    color: ["Red", "Black", "Navy"],
    size: ["XS", "S", "M", "L"],
  },
  {
    productName: "Tight Squeeze",
    productDescription:
      "These skinny jeans are so tight, you'll wonder if they came with a can of oil. Stretchy for the brave-hearted!",
    productPrice: 39.99,
    productCategory: "Skinny Jeans",
    stockQuantity: 90,
    imageUrl: "https://example.com/images/tight_squeeze.jpg",
    brand: "SqueezeWear",
    rating: "4.3",
    onSale: true,
    color: ["Light Wash", "Dark Wash", "Black"],
    size: ["S", "M", "L"],
  },
  {
    productName: "Knit's a Hard Pants Life",
    productDescription:
      "Soft, knitted leggings that make life a little less hard. Perfect for lounging or conquering the world (in comfort).",
    productPrice: 29.99,
    productCategory: "Leggings",
    stockQuantity: 100,
    imageUrl: "https://example.com/images/knit_hard_pants_life.jpg",
    brand: "ComfyChic",
    rating: "4.6",
    onSale: true,
    color: ["Charcoal", "Burgundy", "Black"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Culotta Here!",
    productDescription:
      "These wide-leg culottes are so breezy, you'll feel like you're on vacation - even if you're just getting groceries.",
    productPrice: 39.99,
    productCategory: "Culottes",
    stockQuantity: 70,
    imageUrl: "https://example.com/images/culotta_here.jpg",
    brand: "WindyCity",
    rating: "4.8",
    onSale: false,
    color: ["White", "Beige", "Teal"],
    size: ["XS", "S", "M"],
  },
  {
    productName: "The Fleece Awakens",
    productDescription:
      "Prepare for battle... with the cold! These fleece joggers will keep you warm, no matter how icy it gets out there.",
    productPrice: 45.0,
    productCategory: "Joggers",
    stockQuantity: 85,
    imageUrl: "https://example.com/images/fleece_awakens.jpg",
    brand: "ForceWear",
    rating: "4.9",
    onSale: true,
    color: ["Charcoal", "Black"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Fit to be Tied",
    productDescription:
      "These drawstring pants are so comfortable, you'll be 'tied' to them forever. Adjustable waistband for the perfect fit.",
    productPrice: 32.5,
    productCategory: "Drawstring Pants",
    stockQuantity: 150,
    imageUrl: "https://example.com/images/fit_to_be_tied.jpg",
    brand: "TieStyle",
    rating: "4.4",
    onSale: true,
    color: ["Olive", "Navy", "Gray"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Pants Labyrinth",
    productDescription:
      "Get lost in style with these intricately patterned pants. No need for a map, just confidence.",
    productPrice: 50.0,
    productCategory: "Patterned Pants",
    stockQuantity: 55,
    imageUrl: "https://example.com/images/pants_labyrinth.jpg",
    brand: "MazeWear",
    rating: "4.5",
    onSale: false,
    color: ["Black and White", "Red and Blue"],
    size: ["M", "L", "XL"],
  },
  {
    productName: "Jean-ie in a Bottle",
    productDescription:
      "Rub these jeans, and you might just get three wishes. Or at least three compliments.",
    productPrice: 55.0,
    productCategory: "Jeans",
    stockQuantity: 95,
    imageUrl: "https://example.com/images/jean_ie_bottle.jpg",
    brand: "MagicDenim",
    rating: "4.6",
    onSale: true,
    color: ["Blue", "Faded Black", "Dark Indigo"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Sweat It Out",
    productDescription:
      "Perfect for working out or working on that last slice of pizza. You do you.",
    productPrice: 30.0,
    productCategory: "Sweatpants",
    stockQuantity: 120,
    imageUrl: "https://example.com/images/sweat_it_out.jpg",
    brand: "ChillFit",
    rating: "4.3",
    onSale: false,
    color: ["Black", "Gray", "Olive"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Panta Claus",
    productDescription:
      "These cozy red joggers are making a list, and they're checking it twice! Perfect for the holiday season.",
    productPrice: 35.99,
    productCategory: "Joggers",
    stockQuantity: 70,
    imageUrl: "https://example.com/images/panta_claus.jpg",
    brand: "FestiveGear",
    rating: "4.7",
    onSale: true,
    color: ["Red", "Green"],
    size: ["M", "L", "XL"],
  },
  {
    productName: "Cargo-a-Go-Go",
    productDescription:
      "For when you need to bring everything... and then some. These cargo pants have ALL the pockets.",
    productPrice: 44.99,
    productCategory: "Cargo Pants",
    stockQuantity: 85,
    imageUrl: "https://example.com/images/cargo_go_go.jpg",
    brand: "UtiliWear",
    rating: "4.8",
    onSale: false,
    color: ["Olive", "Khaki"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Chino What You Did Last Summer",
    productDescription:
      "These classic chinos know all your summer secrets... and they're here to help you keep them stylishly under wraps.",
    productPrice: 40.0,
    productCategory: "Chinos",
    stockQuantity: 60,
    imageUrl: "https://example.com/images/chino_last_summer.jpg",
    brand: "SunChinos",
    rating: "4.5",
    onSale: false,
    color: ["Sand", "Gray", "Navy"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Denim Impossible",
    productDescription:
      "Your mission, should you choose to accept it, is to rock these jeans so hard, people won't know what hit them.",
    productPrice: 59.99,
    productCategory: "Jeans",
    stockQuantity: 100,
    imageUrl: "https://example.com/images/denim_impossible.jpg",
    brand: "SpyDenim",
    rating: "4.9",
    onSale: true,
    color: ["Light Wash", "Dark Wash"],
    size: ["M", "L", "XL"],
  },
  {
    productName: "Jogging My Memory",
    productDescription:
      "Can't remember the last time you wore pants this comfy? Don't worry, you'll never forget these joggers.",
    productPrice: 38.0,
    productCategory: "Joggers",
    stockQuantity: 80,
    imageUrl: "https://example.com/images/jogging_my_memory.jpg",
    brand: "FastLane",
    rating: "4.4",
    onSale: false,
    color: ["Charcoal", "Black", "Navy"],
    size: ["S", "M", "L"],
  },
  {
    productName: "Caught Red Cargo'd",
    productDescription:
      "Red hot cargo pants that will make you the center of attention, with more pockets than you can handle.",
    productPrice: 42.0,
    productCategory: "Cargo Pants",
    stockQuantity: 75,
    imageUrl: "https://example.com/images/caught_red_cargo.jpg",
    brand: "FlameWear",
    rating: "4.7",
    onSale: false,
    color: ["Red", "Black"],
    size: ["M", "L", "XL"],
  },
  {
    productName: "Chino You Can Dance",
    productDescription:
      "Chinos so flexible, they'll have you busting moves on the dance floor. Perfect for spontaneous breakdance battles.",
    productPrice: 39.5,
    productCategory: "Chinos",
    stockQuantity: 110,
    imageUrl: "https://example.com/images/chino_dance.jpg",
    brand: "StepStyle",
    rating: "4.8",
    onSale: true,
    color: ["Gray", "Navy", "Khaki"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Palazzo Party",
    productDescription:
      "Every day is a party with these palazzo pants. Wide-leg, flowy, and always ready to celebrate.",
    productPrice: 36.99,
    productCategory: "Palazzo Pants",
    stockQuantity: 95,
    imageUrl: "https://example.com/images/palazzo_party.jpg",
    brand: "BreezyVibes",
    rating: "4.9",
    onSale: false,
    color: ["White", "Beige", "Teal"],
    size: ["S", "M", "L"],
  },
  {
    productName: "Yoga Pants? Namaste Here",
    productDescription:
      "These yoga pants are so comfortable, you'll want to skip the workout and just meditate on your couch.",
    productPrice: 32.0,
    productCategory: "Leggings",
    stockQuantity: 150,
    imageUrl: "https://example.com/images/yoga_pants_namaste.jpg",
    brand: "ZenWear",
    rating: "4.8",
    onSale: true,
    color: ["Black", "Burgundy"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Plaid You Came",
    productDescription:
      "For those days when solid colors just aren't cutting it, these plaid pants will make a statement and then some.",
    productPrice: 48.0,
    productCategory: "Patterned Pants",
    stockQuantity: 45,
    imageUrl: "https://example.com/images/plaid_you_came.jpg",
    brand: "CheckMate",
    rating: "4.6",
    onSale: false,
    color: ["Red Plaid", "Green Plaid", "Blue Plaid"],
    size: ["M", "L", "XL"],
  },
  {
    productName: "Corduroy Crush",
    productDescription:
      "Corduroy pants that will make anyone swoon. Classic, soft, and irresistibly stylish.",
    productPrice: 52.5,
    productCategory: "Jeans",
    stockQuantity: 60,
    imageUrl: "https://example.com/images/corduroy_crush.jpg",
    brand: "RetroRevive",
    rating: "4.9",
    onSale: true,
    color: ["Brown", "Navy"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "Pants-tastic Voyage",
    productDescription:
      "These lightweight linen pants will take you on a journey of comfort and style. Pack your bags, adventure awaits!",
    productPrice: 47.0,
    productCategory: "Linen Pants",
    stockQuantity: 90,
    imageUrl: "https://example.com/images/pants_voyage.jpg",
    brand: "TravelThreads",
    rating: "4.7",
    onSale: false,
    color: ["White", "Beige", "Olive"],
    size: ["S", "M", "L", "XL"],
  },
  {
    productName: "The Pants Are Coming From Inside the House!",
    productDescription:
      "Comfy lounge pants perfect for binge-watching your favorite horror films. Spoiler: they'll never want to leave.",
    productPrice: 33.99,
    productCategory: "Sweatpants",
    stockQuantity: 125,
    imageUrl: "https://example.com/images/pants_inside_house.jpg",
    brand: "CouchComfort",
    rating: "4.5",
    onSale: true,
    color: ["Gray", "Charcoal", "Black"],
    size: ["M", "L", "XL"],
  },
]

const run = async () => {
  try {
    await Product.deleteMany()
    await Product.insertMany(products)
    console.log("Created products!")
  } catch (error) {
    console.error("Error seeding products:", error)
  } finally {
    db.close()
  }
}

run()
